### ISSUE TITLE
Enhancement: exclude NPCs by type

### ISSUE THREAD

**Issue by SR5060** [DanielBoettner/fvtt-loot-populator-npc-5e#5]
Add a setting to only populate loot items on NPC types that are deemed appropriate (e.g. only humanoids, giants, etc.)

**Comment by DanielBoettner** [comment]
Thanks for the interest in the module and creating the issue.
I already thought about that and will include this feature soon.

Currently trying to wrap my head around the most convenient way to create the list to check against.

**Comment by SR5060** [comment]
A similar module uses a comma delimited freetext field in settings to check against. Not the most elegant approach but functional

**Comment by DanielBoettner** [comment]
![image](https://user-images.githubusercontent.com/21986545/122562228-1fcf5600-d043-11eb-9c61-8900bf61d794.png)

Current state of development.

And yes, basically went for the text field as well.
Not yet sure if it will stay that way. But for a first iteration on the feature this should be fine.

**Comment by SR5060** [comment]
Awesome! purely one person's opinion, but I think there are way more types I would exclude vs include (for me, really only populating on humanoid and giant types), so the list would be more efficient as an inclusion setting. There may be other considerations though that I'm not aware of.

**Comment by DanielBoettner** [comment]
Lastest state of development. 
Can be found in linked branch.
Regarding **exclude vs. include**.

That was one angle I was considering.
For now I decided to fetch the available creature types directly from the system.
I'm aware that this (for now) won't allow to blacklist custom creature types.

The reasoning behind excluding instead of including. I'd like to add defaults for creature types later on.

Plants could always get certain plant parts from a specific table.
Beast could get some bones and fur, ....

![game_settings](https://user-images.githubusercontent.com/21986545/122591662-8a908980-d063-11eb-8187-78978744a24a.png)
![module_defaults](https://user-images.githubusercontent.com/21986545/122591661-89f7f300-d063-11eb-9a05-6aead608ba7a.png)
![blacklist](https://user-images.githubusercontent.com/21986545/122591658-895f5c80-d063-11eb-91ab-e0b797eea695.png)

**Comment by SR5060** [comment]
Makes complete sense, and having the types listed out makes that pretty easy anyways. Looks great!
